### ISSUE TITLE
Suggest relevant content

### ISSUE THREAD

**Issue by michelleif** [LD4P/requirements#10]
[DarrenW] When starting to enter data, can CEDAR first try to find an existing record? The existing record might be local or somewhere in LOD (e.g. OCLC or other LOD partners). A smart UI could suggest relevant entities based on access to existing LOD. For example, if we know the author of a new book and start the catalog process from the Author, it could suggest common co-authors, publishers, places of publication, and related works/instances and related subjects etc. In this way, creating new catalog entries could easily reuse existing content (actually existing URIs).

**Comment by michelleif** [comment]
More examples:
Suggest controlled values based on string-based entries: example: some fields will contain transcription of info directly from resource being described, these could be used to fill in other fields, for ex., you transcribe the publication statement, and CEDAR suggests a value you use to fill in a different field that requires a URI for a publisher
Suggest values for one field based on how the cataloger filled out another field (if the serial is by publisher x, its frequency is likely monthly)
Personalization of suggestions (if you are the cataloger for social science materials, then you're going to be re-using a lot of subject headings, even authors, or publishers in that field, so those choices would be ranked higher when you search for them to use in your record)

**Comment by graybeal** [comment]
CEDAR's about-to-be-released Intelligent Authoring service will do some of these things. It will look for existing relationships of values for fields, given the values in other fields, and make suggestions accordingly. 

I'm tempted to claim this is "done", but I suspect you will not be impressed until a lot of metadata has been entered.

**Comment by michelleif** [comment]
closing since this is referenced in https://github.com/LD4P/sinopia_editor/issues/2766
