### ISSUE TITLE
CEDAR: How do you do more than one contributor?

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#102]

**Comment by NancyL** [comment]
I neglected to make the element repeatable. However, having done that it is still not working, I think because there is a repeatable element (role) within that repeatable element. Still looking into this

**Comment by michelleif** [comment]
see #128. is repeatable elements within repeatable elements something that is not possible in CEDAR?

**Comment by graybeal** [comment]
Repeatable elements inside of others should work, but they are not supported (viewable) in spreadsheet view).
