### ISSUE TITLE
LC Editor: Preferred work title: no non-filing character indicator, is this because it’s a work, not an instance?

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#106]

**Comment by kirkhess** [comment]
I don't see the need for non filing characters in a world where search engines have stop lists. We aren't filing cards anymore...but we'll double check what is going on here.

**Comment by michelleif** [comment]
see #100 and #67

**Comment by michelleif** [comment]
is this an editor issue or a cataloging policy issue?
