### ISSUE TITLE
LC Editor: Input subject strings?

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#108]
What does “Input Subject Strings” mean as opposed to searching the lists?

**Comment by jodiw01** [comment]
"Input Subject String" is an option to input the text of a subject string without doing a lookup on each component. A URI is not generated so it's the subject input option of last resort.

**Comment by michelleif** [comment]
would you want a URI generated if possible? a local URI that could be later linked to the canonical URI if the subject string is established somewhere?
see also #
