### ISSUE TITLE
UI beyond forms

### ISSUE THREAD

**Issue by michelleif** [LD4P/requirements#11]
[DarrenW] the UI may need several panels open to display content for links between entities - e.g. a Works/Instances panel, an Authorities panel, and Agent panel (persons, orgs, places). 
[JBG] The idea of having several panels open at once is very far from our UI approach, but we do want elegant ways to leverage information from multiple sources (perhaps not simultaneously -- do your users do more than one task at a time?). Scenarios would be helpful here.

**Comment by graybeal** [comment]
I think this is addressed by the requests to show more metadata, e.g., #17.
