### ISSUE TITLE
CEDAR: Seem to be describing Instance first, instead of Work first as in LC Editor

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#110]

**Comment by NancyL** [comment]
The CEDAR template at the moment is a work with the instance embedded in it. This is because it is difficult at the moment to link two separate templates, something I believe CEDAR is working on.

**Comment by michelleif** [comment]
similar issue described in #30 and in some comments of #9

**Comment by graybeal** [comment]
Looking at a metadata form, it looks to me like the Work is described first, and then the Instance(s) are filled out at the bottom.  So I'm not understanding the original comment?
