### ISSUE TITLE
easier way to see all the data you are inputting

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#111]
both were annoying in the way that inputting each field was so separate; in the Voyager function, the inputting is done directly into a format where all fields are more easily visible; this can be especially important when changing one field should instigate changes to other fields and these are more easily noticeable.

**Comment by graybeal** [comment]
Is the issue in CEDAR that relatively few fields are visible at any one time? I can see entries for fields around the current field, but not a large amount of them.

**Comment by graybeal** [comment]
Added CEDAR issues https://github.com/metadatacenter/cedar-project/issues/843 and https://github.com/metadatacenter/cedar-project/issues/842
