### ISSUE TITLE
Diacritics

### ISSUE THREAD

**Issue by NancyL** [LD4P/requirements#112]
In both editors, it is not possible to tell whether the diacritics entered are valid in the output.

**Comment by kirkhess** [comment]
What is a correct diacritic? 

http://bibframe.org/bibliomata/bfe/development.html#e83299355367427821985530230072665116078

Adresse au Conseil législatif du teritoire d'Orléans
De l'imprimerie du Télégraphe.: Nouvelle-Orléans, 1808
etc.

**Comment by NancyL** [comment]
A diacritic that produces the correct unicode code so that it displays correctly

**Comment by michelleif** [comment]
is this a different issue than #129 and #116?

**Comment by kirkhess** [comment]
I don't see a need to support BIBFRAME->MARC8 so we need to update this standard for BIBFRAME - http://www.loc.gov/marc/specifications/speccharucs.html

The UTF in MARC specifies using NFD, but web browsers do NFC by default.  We should assume NFC moving forward.  Someone should check if CEDAR can handle NFD and continuation characters.
