### ISSUE TITLE
LC Editor: Diacritics

### ISSUE THREAD

**Issue by NancyL** [LD4P/requirements#116]
Needs an easier way to input diacritics. RLIN keyboards seem to work but seem to come out as invalid. Using the 4-digit codes works, but is very clunky

**Comment by kirkhess** [comment]
An integrated IME and transliteration support are good requirements.

In Windows you can switch to the English United States International keyboard which has shortcuts for diacritic entry (aka`+vowel for grave accent, '+vowel for acute accent, :+vowel for umlaut, etc.) which I think mimics how the Apple keyboard works.

Terry Reese is embedding this web-based keyboard in MarcEdit – [https://www.lexilogos.com/keyboard/](https://www.lexilogos.com/keyboard/) which is something we could add as a link. Try that and see if it helps (still clunky obv...I think the International keyboard works pretty well)

**Comment by michelleif** [comment]
Princeton team also reports difficulty with diacritics, no details

**Comment by michelleif** [comment]
see also #112

**Comment by michelleif** [comment]
re Kirk's comment above IME =  input method editor

and adding some details from catalogers at Stanford on how they currently work with diacritics and non-Roman characters in OCLC Connexion.

Diacritics: preferred method (given available methods) is to type the roman letter, and then open a pop-up window (or palette) showing relevant diacritical marks, and choose the one you want. There are "palettes" for each language, so choose the appropriate language and then you see only the appropriate marks. This method is easier than entering numeric codes. Some still use a special RLIN keyboard which you can download via OCLC. There are keyboard shortcuts to bring up these palettes (and catalogers can define their own keyboard shortcuts)

non-Roman script, two methods:
1) type in the text transliterated to roman script. Run the incorporated transliterator to turn it into desired non-Roman language. The advantage of this method (over method 2 below) is that you can use the roman keyboard all the time and don't have to switch. Note that this method does not work properly for Hebrew.
2) set up your machine to have additional keyboard mapping options. then switch back and forth between non-roman and roman keyboard mappings.

**Comment by graybeal** [comment]
I'm not sure I'm familiar with these input methods. On my Mac, if I want to enter Latin characters, I go to the Latin keyboard in the Keyboard Viewer and pick from the keys there, and the characters are entered without issue. The art of entering 4-letter codes (I imagine preceded by a backslash?) may be supported by certain (older?) applications, but is not something I would expect to be used widely across all applications. Further explanation/education for me would be welcome.
