### ISSUE TITLE
LC Editor: Geographic Coverage codes

### ISSUE THREAD

**Issue by NancyL** [LD4P/requirements#118]
Would like to be able to use gac URIs as well as NAF/LCSH for geographic coverage. The hierarchical aspect can be useful

**Comment by kirkhess** [comment]
While you could use the label search http://id.loc.gov/vocabulary/geographicAreas/label/Hungary -> http://id.loc.gov/vocabulary/geographicAreas/e-hu, if you want to type a complex code for Hungary and Yugoslavia aka e-hu--- e-yu--- but you can't make that happen (and that uri doesn't actually resolve.)

We could make this work so you could type in a code like you would for 043 and it would prepend the prefix for the code - this is how marc2bibframe2 works.  Not sure about the hierarchical aspect either but overall it is a good idea to switch to a real geo thesaurus from NAF/LCSH.

**Comment by michelleif** [comment]
this seems to be non-editor issue, just issue of offering the geo thesaurus, which would be a requirement for Questioning Authority
