### ISSUE TITLE
Genre: other vocabularies

### ISSUE THREAD

**Issue by NancyL** [LD4P/requirements#119]
Would like to be able to use other genre vocabularies besides LCGFT (AAT given as example)

**Comment by kirkhess** [comment]
FYI if a vocabulary is in this list -> https://lookup.ld4l.org/authority_list, I should be able to make it work in bfe

**Comment by kirkhess** [comment]
I'm not exactly sure how this would work since the requirement isn't very specific - I got it to work with AAT via the LD4L Authority Lookup Service internally so all of them should be possible.  (I think this is resolved)
