### ISSUE TITLE
LC Editor: Other transliterated parts

### ISSUE THREAD

**Issue by NancyL** [LD4P/requirements#124]
There is no way in this template for entering transliterated statement of responsibility, edition, place of publication, publisher

**Comment by kirkhess** [comment]
I think we could add what you want to a template - I believe we decided to have the main entry as the original language/script not transliterated.

Also, did you review specs for [1XX, 6XX, 7XX, 8XX; X00, X10, X11 – Names - R1 ](http://www.loc.gov/bibframe/mtbf/ConvSpec-1XX,6XX,7XX,8XX-Names-R1p.xlsx) & try some conversions w/transliterated text?

**Comment by jodiw01** [comment]
LC catalogers have entered original and transliterated fields using the existing editor. You just input the data separately.

![image](https://user-images.githubusercontent.com/8515603/42699929-39706df6-8690-11e8-98fd-f46f320236b6.png)
