### ISSUE TITLE
CEDAR: can only enter one identifier

### ISSUE THREAD

**Issue by NancyL** [LD4P/requirements#128]
unable to have more than one type of indentifier or more than one identifier (e.g., unable to have both LCCN and ISBN)

**Comment by NancyL** [comment]
Need to make the field repeatable. This will take a bit of time, since it is inside the Instance element

**Comment by michelleif** [comment]
is it possible to set this up in CEDAR? or is this a feature that is lacking in CEDAR? same issue as #102?

**Comment by graybeal** [comment]
I think this should be straightforward to do inside another element. The only hitch is that you can not access/enter repeating fields inside a spreadsheet view (see #102), but you should be able to in non-spreadsheet view.
