### ISSUE TITLE
CEDAR: Diacritics

### ISSUE THREAD

**Issue by NancyL** [LD4P/requirements#129]
Editor needs an easier way to input diacritics for Latin script languages other than the 4-digit alt codes. I tried the RLIN21 Latin Keyboard, which appeared to work, but it does not create proper unicode according to the W3C Validation Service.

**Comment by NancyL** [comment]
Addition: Turns letters with diacritics entered with 4-digit alt codes into junk. For example: ExperiÃªncias e narrativas em educaÃ§Ã£o

**Comment by michelleif** [comment]
Princeton team also reports difficulty with diacritics, no details.

**Comment by michelleif** [comment]
see also #112

**Comment by michelleif** [comment]
this is part bug (diacritics turn into junk) and part UI/UX (need easier way to enter). just labeling as bug for now so that it doesn't end up solely in the UI/UX category

**Comment by michelleif** [comment]
see also #116

**Comment by graybeal** [comment]
During discussion in the meeting: Part of the challenge is that diacritics are not just used to conform to specific language representations, but also to specify transliteration. (See discussion at https://docs.google.com/document/d/1i0RCdkO11VX6SOs1vcE4a_uOyuXOnLJ_-tm1XEvhXlQ/edit.)  So the overall need is for a way to enter them easily during metadata creation.
