### ISSUE TITLE
CEDAR: Place of publication

### ISSUE THREAD

**Issue by NancyL** [LD4P/requirements#131]
Cannot type place of publication, have to use the vocabulary.  I wanted to input brackets and a question mark

**Comment by michelleif** [comment]
should this be a free-text field? or you want a field that let's you either choose from the vocabulary OR enter free-text? see also

**Comment by graybeal** [comment]
Could achieve this by adding a 'Place of Publication comment' field to the template right after this field. But in the end controlled terms are always totally controlled.
