### ISSUE TITLE
in RDF, retain order of multiple values in repeatable field

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#138]

**Comment by eslao** [comment]
It would be nice to be able to reorder headings (e.g subject headings). It is possible to copy and paste cells, but not rows in the subject form. Could arrows to move rows and down on the subject heading form be added?

**Comment by michelleif** [comment]
and would order of subject headings need to be captured in resulting RDF, using rank?

**Comment by graybeal** [comment]
It should be possible to copy and paste rows in a spreadsheet, although possibly other issues like #145 made this work incorrectly.

The suggestion to add up/down arrows for rows is very nice, but possibly beyond our means with this third-party spreadsheet software.

CEDAR will preserve ordering via the JSON, but as Michelle suggests if it should be preserved in RDF a dedicated order field will be needed.

**Comment by michelleif** [comment]
@eslao is this a requirement for our RDF, to order the subject headings?

**Comment by michelleif** [comment]
generalizing this to maintaining order among values in a repeating field, to see if we need this in Sinopia. even if this is a requirement, it might be that template / ontology has to make it possible (such as Primary Contributor / Other Contributors)

**Comment by michelleif** [comment]
this works now. set the field attribute to "ordered" when creating the template.
