### ISSUE TITLE
BFE: cannot edit saved descriptions

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#142]
Once you’ve saved, you cannot edit; only delete and start over again.

**Comment by michelleif** [comment]
ask Kirk if this is fixed and find out if stanford and princeton had the same experience

**Comment by kirkhess** [comment]
We've done 4k+ of these for the BIBFRAME Pilot - the bibframe.org version has been reset multiple times while we do development.  I just saved, edited, saved, edited no problem.

**Comment by michelleif** [comment]
re Sinopia, it is possible to edit saved, so closing this in Sinopia context
