### ISSUE TITLE
CEDAR: entering multiple contributors is confusing at best

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#148]

**Comment by michelleif** [comment]
any ideas about how you would like a UI to work for entering multiple contributors? (or multiple whatevers)

**Comment by graybeal** [comment]
It isn't obvious to users how to (for example) enter a second element for a repeatable element. (Some of the strange behaviors when switching views and copying rows also can contribute to this confusion.)

As Michelle asks, any particular recommendations would be welcome.
