### ISSUE TITLE
BFE: not clear how to create instance for an existing work

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#149]

**Comment by michelleif** [comment]
is this a UX issue? it is possible to create instance for existing work just not clear how? or there's no way to do it?

**Comment by graybeal** [comment]
2 issues for CEDAR. 1) No ready link exists to create an Instance while in the context of a Work metadata form. 2) When one is viewing or editing an existing Work in CEDAR, the model does not understand that the ID of this current thing (the Work) can be used as a basis for creating  a metadata form for an Instance (that references the Work ID).

Item 1 will will be addressable when we add static fields for templates (soon!): It will be possible to add a link that is visible in the Work's metadata form,  to create a metadata form for an Instance. It just won't be possible to couple the special knowledge about the Work inside the metadata form for the Instance.

**Comment by eslao** [comment]
Not sure; someone more expert in using BFE might be able to say whether we should be able to do it. Further comments from cataloger: "unable to create BF instance for  work ; completed form 3 times, save unsuccessful ; instructions on editor would be helpful"

**Comment by kirkhess** [comment]
You create a new instance, and then click Instance Of BIBFRAME Work, type a title in the lookup field and save changes. However, the work lookup is only internal to LC, which is why this probably isn't that obvious.
