### ISSUE TITLE
CEDAR: performance issues

### ISSUE THREAD

**Issue by michelleif** [LD4P/requirements#150]
(from Amber when testing in 2017 for ArtFrame:	--The CEDAR UI is SLLOOOOW and can get “bogged” down. 
--Not uncommon to have CEDAR freeze

**Comment by graybeal** [comment]
Speed has been improved since 2017, though more optimization may be needed for certain use cases. Please let us know if users see either issue now.

**Comment by eslao** [comment]
This issue has definitely been observed by Harvard catalogers.

**Comment by michelleif** [comment]
adding comment from Craig (Harvard) that it seems especially slow in the afternoon (east coast time)--Craig's comment refers to slowness during template editing (although the June/July-2018 cataloger trial was focused on adding metadata, Craig also looked at template creation)
