### ISSUE TITLE
better way to see what you've entered

### ISSUE THREAD

**Issue by michelleif** [LD4P/requirements#154]
This ticket is to give more context to catalogers' wish to "preview", based on discussion with group of Stanford catalogers.

Catalogers would like to see all the metadata they've entered in a form, all at once. In CEDAR, fields/sections are collapsed, which prevents you from seeing everything. In the LC Editor, you don't see all the information you need (will have to get more details on this if specifics are needed).

The need for a "preview" is not really a need to go to another screen and see a view that is different from the metadata creation view. It's a need to see all the metadata you have created in the form.

See also #104, #112, #113

**Comment by michelleif** [comment]
also noting that in OCLC Connexion there is a visual indication of the info that you've added vs info that was already in a record

**Comment by graybeal** [comment]
In CEDAR you can unfold fields and sections (and convert multiple large flat lists to tables). Does it satisfy this need  if there is a single button to unfold everything? Or is part of the concern to have a format that presents as much content as possible.

**Comment by graybeal** [comment]
related to #111?

**Comment by michelleif** [comment]
from Harvard: would like to have a "Open all populated elements" command

**Comment by graybeal** [comment]
Captured for CEDAR as https://github.com/metadatacenter/cedar-project/issues/708

**Comment by michelleif** [comment]
in SInopia, once you enter data, the section remains expanded unless you collapse, so this is not an issue
