### ISSUE TITLE
CEDAR: Could we bring in other ontologies to include elements not already in BioPortal?

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#155]
(Such as our BF extensions?)

**Comment by graybeal** [comment]
Yes, this is done (for now) by adding them to BioPortal. (They can be made private if you don't want them visible outside of CEDAR.) Other approaches are being evaluated for the longer term.

**Comment by NancyL** [comment]
the Performed Music Ontology, some if not all of the ontologies from the Rare Materials/Artframe ontology are in BioPortal. Also various other library ontologies and vocabularies (some of these more successful than others)
