### ISSUE TITLE
CEDAR: General ergonomics

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#156]
Neither the template nor the metadata form is easy to navigate from an ergonomic standpoint; lots of mousing required

**Comment by graybeal** [comment]
Captured in CEDAR as https://github.com/metadatacenter/cedar-project/issues/708 (also https://github.com/metadatacenter/cedar-project/issues/751, and https://github.com/metadatacenter/cedar-project/issues/752)

**Comment by michelleif** [comment]
keyboard navigation has been improved in Sinopia
