### ISSUE TITLE
CEDAR: It would be good if the Work and Instance sections were more clearly demarcated

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#159]
(This is probably a template issue.)

**Comment by graybeal** [comment]
I believe this refers to the RDF output in #160, and how well that is displayed.

**Comment by michelleif** [comment]
@eslao I think this is solvable in Sinopia with how templates are set up. Especially when Work and Instance template are separate. If not please reopen this ticket and provide more info thank you
