### ISSUE TITLE
in Preview, use URI prefixes and differentiate among Work and Instance assertions

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#160]
Use of prefixes, rather than full URI strings, would help. Catalogers would also like it if it work and instance assertions were somehow demarcated.

**Comment by graybeal** [comment]
Note for CEDAR team: I believe output in this case refers particularly to RDF output, both as displayed at bottom of metadata form and as exported.

**Comment by michelleif** [comment]
@eslao speaking of Sinopia, is this still something you would like to see in the Preview?

**Comment by michelleif** [comment]
since this ticket was created, preview was enhanced with choice of different views, closing this because the preview is working well now from all accounts. also, Work and Instance assertions are not in the same template (at least for PCC templates)
