### ISSUE TITLE
CEDAR: date stamp error

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#161]
Metadata creation date does not take the exact date. It keeps defaulting to the previous date. “2018-07-27” displays as “2018-7-26”.

**Comment by eslao** [comment]
Is Cedar taking the user's time zone into account when displaying date/time?

**Comment by graybeal** [comment]
Captured as a CEDAR issue, now being worked on: https://github.com/metadatacenter/cedar-project/issues/784.

**Comment by graybeal** [comment]
See also #87

**Comment by michelleif** [comment]
CEDAR-specific issue, closing for Sinopia
