### ISSUE TITLE
CEDAR: Do not collapse fields after editing

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#164]
Related to issue #46, a cataloger asks: "Please, can we have the default be to have all the data we entered open for viewing. Especially important for vetting glitches like the one mentioned above where the information for Type of Contributor and Name disappeared upon saving. How will I know this has happened otherwise?"

**Comment by NancyL** [comment]
I suspect it might be a bit more complicated than this--that catalogers would like to be able to set their own defaults (and change them if they want)?

**Comment by michelleif** [comment]
re Sinopia, once data is entered it is not collapsed automatically, so not an issue
