### ISSUE TITLE
BFE: Place of publication is a string

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#165]
Should we consider making Place of Publication actionable by controlling it (but leaving the option of adding a place of publication that has no authority record to back it up?). This is one thing that CEDAR does that BFE doesn’t do.

**Comment by eslao** [comment]
(Not sure if this is a template issue, or something baked into the tool or ontology files.)

**Comment by NancyL** [comment]
This is a template issue. However, for either template, you can either have a controlled term or a string; you can't mix them. Not necessarily a bad thing (you might actually want both the controlled term and a transcription of the place name), but you would have to have 2 separate fields in the template

**Comment by michelleif** [comment]
is it a desired feature to have a field that is controlled, but also gives the cataloger the ability to enter something that is not in the controlled vocabulary? see #99

**Comment by michelleif** [comment]
as of release 1.1.0, Sinopia allows you to enter a literal in a lookup field, if you don't find a controlled value you want to use
