### ISSUE TITLE
When creating metadata, get information about values in a value list

### ISSUE THREAD

**Issue by michelleif** [LD4P/requirements#17]
applies to entity lookup also not just simple list of values

When you’re filling in a metadata form, and you come to a field that has a value list with values from an ontology, there should be a way to see some additional information about the values, so you can make sure you’re choosing the best one. There could be a choice of turning on and off a verbose display so you could choose whether or not to see this information about the values (what ontology they’re from, definition if there was one in the ontology, etc.)

**Comment by michelleif** [comment]
development estimate from earlier discussion: >= 2 person-weeks

**Comment by michelleif** [comment]
this is a requirement for interaction with Questioning Authority-type lookup service

**Comment by eslao** [comment]
Related comments from Harvard group's notes: 'We need more information on lookup for Place. “City of San Francisco”--is this the correct San Francisco? We can’t see the entity it’s linking to. It would be good to be able to input free text if an entity is not available. (Can the cataloger create a record for such an entity as needed, or will a more complete authority file be added to Cedar?)'
