### ISSUE TITLE
have a cartographic coordinate data type

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#173]
Cartographic coordinates expressed as degrees, minutes, and seconds do not display properly. I used an online widget to convert to decimal units.

**Comment by NancyL** [comment]
Is this a diacritics issue?

**Comment by michelleif** [comment]
@eslao have you tried this in Sinopia and does the same problem happen there?

**Comment by michelleif** [comment]
closing this as it can be covered in https://github.com/LD4P/sinopia_editor/issues/2727
