### ISSUE TITLE
BFE: editing values after initial input

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#175]
Even though it says you can, you can’t always go back to edit the text or values you have input into a “field”. Sometimes you can (e.g. Title information), but not always (e.g. Note). This is true for both Work and Instance.

**Comment by eslao** [comment]
More from cataloger notes: "Once I have entered the Instance information,  when I go back to Edit, I don’t have the option of saving my later edits--there is no save button. There is a work-level note in my instance description that I cannot get rid of, and I would like to add the 074 GPO Item number from the MARC record as an additional Identifier for the Manifestation.  However, I can save later edits made to the work-level description"

"Apparently, if you create the Work-level first, it’s the opposite situation: You can save later edits made to your instance-level, but not to your work"

**Comment by michelleif** [comment]
considering this only against Sinopia; Sinopia does allow you to edit previous input and then save edits
