### ISSUE TITLE
CEDAR: lookups are opaque

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#177]
If you want to check the accuracy of the term you’re assigning (e.g. is it the correct name of the city), you have to open the template and search by clicking on the little triangular icon up at the top next to Element Description. This is somewhat clunky and inconvenient. Is there any access to searching for the term in BioPortal from within the Metadata form?

**Comment by graybeal** [comment]
Not currently, though we do have at least one task identified along these lines: https://github.com/metadatacenter/cedar-project/issues/748

**Comment by michelleif** [comment]
looking at these older evaluations to see if any are relevant to things we might want to enhance in Sinopia; Sinopia does provide extended context for many vocabularies. or allows you to click on the selected term and go to the term's URI. @eslao do you need more in Sinopia to let you check the accuracy of terms from a lookup?

**Comment by michelleif** [comment]
re clicking on a term to go to the URI, that is a feature request here: https://github.com/LD4P/sinopia_editor/issues/1663
