### ISSUE TITLE
Specify that the allowed values for a field depend on the value entered in another field when metadata is created

### ISSUE THREAD

**Issue by cmharlow** [LD4P/requirements#179]
A29: Specify that the allowed values for a field depend on the value entered in another field when metadata is created. see example in spreadsheet

PO: low priority

**Comment by michelleif** [comment]
also: be able to determine what fields are shown, based on the value of another field

(example: https://github.com/LD4P/sinopia_editor/issues/2732)

**Comment by justinlittman** [comment]
No current use cases, so closing.
