### ISSUE TITLE
Add the ability to preview records created in Sinopia in a format other than plain RDF triples

### ISSUE THREAD

**Issue by a-cohen** [LD4P/requirements#188]
It might be nice to have the option to preview data created in the linked data editor in a format other than plain RDF triples (ie. RDF-XML or JSON-LD). Similar to how the LC editor has the option to preview the data in three different formats.

This might make it easier for catalogers to look through their data (as long as they are familiar with the format), rather than try to parse through a wall of triples.

**Comment by michelleif** [comment]
Hi @a-cohen, going through older tickets in preparation for new Sinopia work cycle. as of release 1.3.0 Sinopia preview gives choice of table, N-triples or Turtle. do you still need RDF-XML or JSON-LD view within Sinopia?

**Comment by a-cohen** [comment]
I think both RDF-XML and JSON-LD would be quite helpful. Especially RDF-XML as LC's BIBFRAME to MARC converter expects it, and that would make conversion much easier.

**Comment by michelleif** [comment]
thanks! do you need this on a record by record basis, to preview in those formats. Or is it more that you need those exported out of Sinopia in a batch basis?

**Comment by a-cohen** [comment]
If possible, both would be great! I know I would definitely like the option to choose the serialization of the exports, but it would also be nice on a record by record basis.

**Comment by NancyL** [comment]
+1 to all the above!

**Comment by michelleif** [comment]
for export use case see also LD4P/sinopia_exporter#14

**Comment by michelleif** [comment]
closing this as the preview is now avail as JSON-LD
