### ISSUE TITLE
Collapsible editor sections

### ISSUE THREAD

**Issue by cmharlow** [LD4P/requirements#189]
C5: Collapse and expand sections of a long form for easier navigation

**Comment by michelleif** [comment]
closing this assuming our UX improvements make this no longer an issue

**Comment by NancyL** [comment]
Now to get this in the right place. RTs still cannot be collapsed if they are mandatory or they are populated with metadata. There was an expressed wish that one could still collapse these.

**Comment by michelleif** [comment]
ok reopening this and including it in list of issues to be prioritized for next work cycle

**Comment by michelleif** [comment]
@NancyL is this still an issue now that we have left nav bar?
