### ISSUE TITLE
Editing a template when other templates are based on it, and metadata has been created

### ISSUE THREAD

**Issue by michelleif** [LD4P/requirements#19]
When templates are revised, need some mechanism for determining whether and how to revise 
(a) templates based on those templates and 
(b) corresponding metadata records

**Comment by graybeal** [comment]
Partly addressed in https://github.com/metadatacenter/cedar-project/issues/608 and https://github.com/metadatacenter/cedar-project/issues/861.

**Comment by michelleif** [comment]
requirements for versioning are being worked on for WC4, so closing this
