### ISSUE TITLE
specify list of allowable values for a field (as opposed to specifying a whole vocabulary)

### ISSUE THREAD

**Issue by cmharlow** [LD4P/requirements#190]
A12: Limit a field's allowed values to a set of terms from one or more published vocabularies

For dev MVP, this means ability for profile writer to specify or provide the look-up list themselves (instead of relying on an external look-up list). 

Alternatively, this could be an implementation that filters the external look-up list (see LD4P/sinopia#31).

**Comment by justinlittman** [comment]
Current approach of always using an authority is acceptable.
