### ISSUE TITLE
Metadata creator can view more than one form at a time

### ISSUE THREAD

**Issue by michelleif** [LD4P/requirements#21]
One example: you can have a Work with more than one related Instance, and you want to look at metadata for the Work and each related Instance at the same time.
[JBG] The key question is, do both forms have to be open at the same time? (Why?) So far we have found it is possible to expect the work to flow sequentially, OR if not, we intend to enable embedding (of elements in templates). Possibly you propose the limiting case where embedding doesn't make sense.

**Comment by michelleif** [comment]
development estimate for CEDAR from previous discussion: >= 2 person-months

**Comment by michelleif** [comment]
this might be another example, unless Work and Instance are in the same form?: Original cataloging. You have to make a new Work and then an Instance of that Work. Should support both (1) starting at Instance and going off to create and then refer to the Work, or (2) starting by creating the Work and then creating the linked Instance.

**Comment by michelleif** [comment]
may be related to #30, #91 and #110
right now you can see more than one form by having more than one browser window open

**Comment by michelleif** [comment]
adding information from discussion with catalogers at Stanford: in current system (OCLC Connexion), you can open multiple forms (windows) at once and view them tiled. or you open another instance of the editor.

**Comment by graybeal** [comment]
Opening multiple browser windows can achieve viewing multiple windows at one time. Is there something special about doing it within the tool that this doesn't achieve?
