### ISSUE TITLE
cataloger choose class from a dropdown for instance type

### ISSUE THREAD

**Issue by michelleif** [LD4P/requirements#27]

**Comment by amberbilley** [comment]
This is especially important when the necessary subclass is contingent on the source or type of data.

**Comment by michelleif** [comment]
**Scenario provided by Amber**
Objects in libraries have a bunch of different kinds of identifiers. We need to record the actual identifier and then what type of identifier it is (ISBN, ISSN, LCCN, etc). I want one repeatable box, where I can enter the identifier data and select the subclass of Identifier to record what kind of sub-class/Instance Type that data represents.

**Solution already available in CEDAR**

1. create an element
1.  in this element, add 2 fields (whatever you want to call them):
    1. field 1: "Type of Identifier"
        * this is the field where the cataloger will choose what type of identifier they are naming
        * For this field, constrain the value to the subclasses of bf:Identifier by going to Values/Search, then find bf:Identifier and choose "branch" and "add descendants of this field"
    1. field 2: "Identifier Value"
1. give the entire element the class bf:Identifier (do this at upper right)
1. save this element
1. now in your Work template (or Item or Instance or whatever), add the element.
1. and pick the property bf:identifiedBy to relate this element to the template
1. and also, make this element repeating so that the cataloger can add multiple identifiers if needed
1. save the template

when the cataloger fills out (populates) the Work template, in the Identifier "section" they will see the "Type of Identifier" field, and the choices will be ANSI, ISSN, etc.

and, the cataloger can add as many identifiers as needed, giving each one a type.

**sample Element and Template in CEDAR**
element is called "Identifier"
template is called "Template with Identifier Element"
