### ISSUE TITLE
Associate field with a class

### ISSUE THREAD

**Issue by michelleif** [LD4P/requirements#3]
associate a field with a class: do we need this? not sure if that is needed, as long as you can associate element with a class, which you can. Need some examples to look at. (this used to be a feature in CEDAR)

**Comment by michelleif** [comment]
is this in the public version of CEDAR?

**Comment by michelleif** [comment]
need some scenarios to test

**Comment by graybeal** [comment]
CEDAR now supports first-class fields, so this should work. Please verify.
