### ISSUE TITLE
when creating a template, choose among ontology versions

### ISSUE THREAD

**Issue by michelleif** [LD4P/requirements#33]
does CEDAR let you choose among ontology versions when developing a template? we want to do this, for example, you have a dependency on an older version

**Comment by graybeal** [comment]
The only way to do this currently is to make a copy of the ontology version you want to cite, as another ontology. BioPortal does not support prior versions as part of a single ontology.

Reference https://github.com/metadatacenter/cedar-template-editor/issues/696 for detailed ticket related to this request.
