### ISSUE TITLE
CEDAR: RDA instructions needed

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#40]
Why are only some RDA instructions referenced? Or, is the plan to eventually have them all referenced? Also, is the plan to have the RDA Toolkit launch in another window when the question marks are clicked?

**Comment by michelleif** [comment]
Up to template creator to do help text (references to instructions). Ideally the template creator would be able to put links in the help text. So cataloger could read the help text, and see that there is a link to RDA Toolkit, and click to launch it if they wanted. The feature lacking in CEDAR is the ability to put links in the help text. In some cases there is more than one hyperlink we want to put in the help text (link to two different RDA rules), so it can't just be "link this whole line of helptext to a single URL"

**Comment by michelleif** [comment]
see also #15

**Comment by graybeal** [comment]
CEDAR has plans to add more flexible help contents for each field.

**Comment by NancyL** [comment]
There are some instructions in the help contents, though a minimum at this time.
