### ISSUE TITLE
CEDAR:  display of subject headings

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#44]
It would be nice to be able to see all of the subject headings on the same screen instead of having to page forward or toggle the view (although toggling does allow for easier entering of multiple headings)

**Comment by graybeal** [comment]
This request is to see (by default, and within reason) the entries of an array without having to click through the array indices or go to spreadsheet mode. Might defaulting to spreadsheet view for arrays be an acceptable approach?
