### ISSUE TITLE
CEDAR: field contents disappear when re-clicked

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#46]
Why does re-clicking in a form field cause the field contents to disappear? For example, under Geographic coverage, I entered United States and selected United States of America from the pre-populated list. When I clicked anywhere in the field after United States of America was selected (not on the little x), the contents disappeared. Also, Ctrl-Enter did NOT work to save the information; I HAD to click OK.

**Comment by eslao** [comment]
I found the same issue when adding multiple contributors and then toggling back and forth between them -- wasn't sure if things weren't saving to begin with, or whether my subsequent actions removed data somehow.
