### ISSUE TITLE
CEDAR: Instance of questions

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#51]
·         "Provision activity" doesn't imply "publication information" - perhaps there can be pop-ups that tell us what information is expected in a particular field?

·         Again, too many clicks. "Place" should open automatically to the input box.

·         How do we enter multiple place names? Some instances are published in more than one place (or, rather, have more than one place listed).

·         When there is a look-up ("Type of Contributor", for example), some clue about expected values would be helpful. I thought "publisher" should be entered here, but that returned "No Results".

·         Copyright date: it isn't clear why entering 2017 causes the copyright date to be stored as 2016-12-30. Are we supposed to use zeros for month and day?

**Comment by michelleif** [comment]
mutiple issues in this ticket:

issue of repeating fields/elements (entering multiple place names) is covered in #102
issue about dates not saving as entered (copyright date) is covered in #87

UI/UX issues: 
1. "Again, too many clicks. "Place" should open automatically to the input box."
2. "perhaps there can be pop-ups that tell us what information is expected in a particular field?" and "some clue about expected values would be helpful"
3. "Are we supposed to use zeros for month and day?"

**Comment by michelleif** [comment]
Peter re 2. "perhaps there can be pop-ups that tell us what information is expected in a particular field?" and "some clue about expected values would be helpful":

there is potential for pop-ups to tell you what info is expected in a field, it's the little question mark you can mouse-over. it's only present if the template creator added help text, like the RDA instruction numbers. Does this mouse-over help text do what you want? (provided it is filled in by template creator of course)
