### ISSUE TITLE
CEDAR: controlled fields label

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#82]
For controlled fields it would be good to choose a more traditional label, or else give the source of the controlled terms. One time I found myself clicking through every letter of the alphabet waiting for the drop-down menu to appear in order to understand the terms the field was expecting.

**Comment by michelleif** [comment]
--by "traditional label" do you mean the actual name of the field?
--could the part about "giving the source of the controlled terms" could be done in the tooltip/help text for a field
