### ISSUE TITLE
CEDAR: funkiness with dates

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#87]
There is something really funky going on with dates (copyright, metadata). I ended up having to enter the date as date+1 day in order to get the date I wanted. Nice autocorrection of false leap years, though!

**Comment by NancyL** [comment]
It's also interesting that "2018" defaults to "2017-12-30". We wonder why not the 31st?
Copyright was encoded as a date field, but only seems to accept full dates down to the day, without the year. Will change this to a text string temporarily

**Comment by graybeal** [comment]
Yes, the date picker had some bugs and we have removed it. We likely will add another date picker before too long.
