### ISSUE TITLE
LC Editor: plus sign confusion

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#88]
In cases where the plus sign has to be clicked, it needs to be made clear that one has to click the plus sign before clicking the Save changes button to add content.

**Comment by pmgreen** [comment]
Also, why are there some places where there is no plus sign? The form should be consistent (i.e. the Enter key should behave a certain way, all or none of the fields should have a plus sign, etc.)

**Comment by jodiw01** [comment]
Non-repeatable fields do not have plus signs
