### ISSUE TITLE
LC Editor: authorized access point?

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#90]
It's not clear what to enter for Authorized Access Point Representing the Work. Perhaps a pop-up example would be helpful? The authorized access point for a work is sometimes a combination of a name and title. Are we to enter the information as indicated in the RDA Toolkit examples?

**Comment by paulfrank7** [comment]
You would enter the RDA authorized access point for the work as described in RDA 6.27. This element is a part of the Bf Editor as a bridge for catalogers who would create a MARC name-title authority record for a work, or provide the authorized access point form in the bibliographic record through a 1XX + 240 MARC field array. The authorized access point box is not critical to the functioning of the Bf Editor, or to any RDF descriptions created in the Editor.
