### ISSUE TITLE
LC Editor: work information not saved

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#91]
I chose Instance under Monograph and entered Work information because the Work didn't exist. After I clicked "Save changes", I was returned to the BF Instance form, but none of the Work information I created was present. I expected to see the Work information I had just created so that I could continue with creating Instance information.

**Comment by jodiw01** [comment]
The information from the Work profile doesn't automatically transfer to the Instance profile. When you are editing an Instance, the Work data can be accessed by clicking on the yellow pencil. Here's an example from the LC editor:

![image](https://user-images.githubusercontent.com/8515603/42697539-5e8f3682-8689-11e8-8681-e204957b6be8.png)

**Comment by michelleif** [comment]
this situation is covered in # "connect templates", need an easier way to work to and from things that are described on different pages/forms
