### ISSUE TITLE
LC Editor: authority record elements in Work form?

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#92]
Why are there authority "record" elements when entering Work information? Are we to re-create authority information here, or is this so that we can create an authority record if none exists?

**Comment by kirkhess** [comment]
Sort of - what this allows you to do is create a stub for an authority record which could be created as a new authority as part of whatever process you have for storing the RDF. We were considering doing this as part of the pilot, but we haven't done it yet.
