### ISSUE TITLE
LC Editor: subjects confusion

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#93]
For Subjects, it isn't clear if the main subject should be repeated each time when using different subdivisions. It isn't clear to which main heading the components refer. Or, is this just creating facets and if we want pre-coordinated headings, should we enter the subject strings?

**Comment by jodiw01** [comment]
What are some examples of subject headings that you would like to input?

**Comment by paulfrank7** [comment]
Yes, the main subject should be repeated when using different subdivisions. Often a pre-coordinated heading is supported by an authority record, in which case you can just search it in the look-up.
