### ISSUE TITLE
LC Editor: Why preview before save?

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#95]
Why must we first preview then save? I understand for the first time we create the description, but what if we make a minor edit? There's no need to preview the RDF in that case, right?

**Comment by kirkhess** [comment]
The first iteration of the editor the preview was the end - there was no saving, you could copy and paste out the RDF/XML in the preview. All the buttons should be on the first page (so preview/save/post/cancel) I'll add that as a bfe issue.
