### ISSUE TITLE
LC Editor: entered instance info disappeared?

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#97]
I added an Instance to a Work I created, and when I saved it and retrieved it, the Instance information was no longer present on the form although I could see it in the RDF. Shouldn't the Work and Instance(s) display together? When I click BIBFRAME Instance, none of the Instance information is displayed, so it looks like there isn't already an Instance.

**Comment by kirkhess** [comment]
This is also not intuitive apparently - you have to click the pencil to edit, the instance button makes a new instance (since you can have more than one).
