### ISSUE TITLE
CEDAR: Place of origin of the work requires selection of matching value – should be free form

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#99]

**Comment by michelleif** [comment]
this is a template configuration issue. unless you need a field where it can be a dropdown but if what you want isn't in the list of matching values, you can enter your own. that is lacking in CEDAR. see also #108

**Comment by graybeal** [comment]
Right, the workaround for now is to create an additional field for any non-controlled term. Someday we will add that as an option on controlled term fields.
